In [1]:
import pandas as pd 
import os 
import openpyxl
import re
from openpyxl import load_workbook
import glob
import os
import numpy as np
from functools import reduce

1. open work book
2. open sheet from the list of sheet_names
3. for each sheet:
      - a. save variables:
           - State
           - Prior_Quater
           - Line
           - Waiver_Type
           - Waiver_Number
           - Waiver_Name
           - Type
           - Quarter_Ended
      - b. re-open sheet with # of skipped rows as dataframe
      - c. create new columns, insert saved variables 
      - d. save the sheet as csv 
4. open csv files as dataframes and concadinate
5. regex the new rows

In [ ]:
# pages 2, 3, 4, 5 have 11 rows same columns

In [ ]:
book = openpyxl.load_workbook('Varsha-Transformation/Transformation/5-64.21UPWAV-TN-1-2022-10B.xlsx')

sheet = book.active

In [ ]:
State = sheet['A4'] # Column A and Row 4
Prior_Quater = sheet['A6']
Line = sheet['A7']
Waiver_Type = sheet['A8']
Waiver_Number = sheet['A9']
Waiver_Name= sheet['A10']
Type = sheet['A11']
Quarter_Ended = sheet['A5']
df = pd.read_excel("Varsha-Transformation/Transformation/5-64.21UPWAV-TN-1-2022-10B.xlsx",skiprows=11)
df = df.rename(columns={"Unnamed: 0": "Category", "Unnamed: 1": "Category Description"})
df.insert(7,"State", State.value, True)
df.insert(8, "Quarter_Ended", Quarter_Ended.value, True)
df.insert(9,"Prior_Quater", Prior_Quater.value, True)
df.insert(10,"Line",Line.value, True)
df.insert(11,"Waiver_Type",Waiver_Type.value, True)
df.insert(12,"Waiver_Number", Waiver_Number.value,True)
df.insert(13,"Waiver_Name",Waiver_Name.value, True)
df.insert(14,"Type",Type.value, True)

In [ ]:
df.head(1)

In [ ]:
df.to_csv('5.csv')

In [ ]:
# pages 6 nad 7 ahve 9 lines of header

In [ ]:
book = openpyxl.load_workbook('Varsha-Transformation/Transformation/7-64.21UWAIV-TN.xlsx')

sheet = book.active

In [ ]:
State = sheet['A4'] # Column A and Row 4
#Prior_Quater = sheet['A6']
#Line = sheet['A7']
Waiver_Type = sheet['A6']
Waiver_Number = sheet['A7']
Waiver_Name= sheet['A8']
Type = sheet['A9']
Quarter_Ended = sheet['A5']
df = pd.read_excel("Varsha-Transformation/Transformation/7-64.21UWAIV-TN.xlsx",skiprows=9)
df = df.rename(columns={"Unnamed: 0": "Category", "Unnamed: 1": "Category Description"})
df.insert(6,"Deferral Disallowance C.I.N. No.",np.NaN, True)
df.insert(7,"State", State.value, True)
df.insert(8, "Quarter_Ended", Quarter_Ended.value, True)
df.insert(9,"Prior_Quater", np.NaN, True)
df.insert(10,"Line",np.NaN, True)
df.insert(11,"Waiver_Type",Waiver_Type.value, True)
df.insert(12,"Waiver_Number", Waiver_Number.value,True)
df.insert(13,"Waiver_Name",Waiver_Name.value, True)
df.insert(14,"Type",Type.value, True)

In [ ]:
df.head(1)

In [ ]:
df.to_csv('7.csv')

In [ ]:
df1 = pd.read_table('2.csv', sep=',').drop(columns='Unnamed: 0')
df2 = pd.read_table('3.csv', sep=',').drop(columns='Unnamed: 0')
df3 = pd.read_table('4.csv', sep=',').drop(columns='Unnamed: 0')
df4 = pd.read_table('5.csv', sep=',').drop(columns='Unnamed: 0')
df5 = pd.read_table('6.csv', sep=',').drop(columns='Unnamed: 0')
df6 = pd.read_table('7.csv', sep=',').drop(columns='Unnamed: 0')

In [ ]:
df1

In [ ]:
merged_df = pd.concat([df1, df2, df3, df4, df5,df6])

In [ ]:
merged_df.to_csv('first_6.csv', index=False)

In [ ]:
df=pd.read_csv('CMS64_TN_first_6.csv')

In [ ]:
df["State"] = df["State"].str.replace(r'.*:', '')
df["Line"] = df["Line"].str.replace(r'.*:', '')
df["Quarter_Ended"] = df["Quarter_Ended"].str.replace(r'.*:', '')
df["Prior_Quater"] = df["Prior_Quater"].str.replace(r'.*:', '')
df["Waiver_Type"] = df["Waiver_Type"].str.replace(r'.*:', '')
df["Waiver_Number"] = df["Waiver_Number"].str.replace(r'.*:', '')
df["Waiver_Name"] = df["Waiver_Name"].str.replace(r'.*:', '')
df["Type"] = df["Type"].str.replace(r'.*:', '')

In [ ]:
df.to_csv('CMS64_TN_1.csv',index=False)

In [2]:
df=pd.read_csv('CMS64_TN_1.csv')

In [3]:
df

,Category,Category Description,Total Computable,FMAP,CHIP,Total Federal Share,Deferral Disallowance C.I.N. No.,State,Quarter_Ended,Prior_Quater,Line,Waiver_Type,Waiver_Number,Waiver_Name,Type,FMAP Percent
0,1A,Premiums Up To 150% Of Poverty Level - Gross P...,29301.0,0.0,23620.0,23620.0,NaN,Tennessee,3/31/2022,4/2021,10B,1115,11W00369/4-01,EG8 Med Exp Child,U2,NaN
1,1B,Premiums Up To 150% Of Poverty Level - Cost Sh...,0.0,0.0,0.0,0.0,NaN,Tennessee,3/31/2022,4/2021,10B,1115,11W00369/4-01,EG8 Med Exp Child,U2,NaN
2,1C,Premiums Over 150% Of Poverty Level - Gross Pr...,0.0,0.0,0.0,0.0,NaN,Tennessee,3/31/2022,4/2021,10B,1115,11W00369/4-01,EG8 Med Exp Child,U2,NaN
3,1D,Premiums Over 150% Of Poverty Level - Cost Sha...,0.0,0.0,0.0,0.0,NaN,Tennessee,3/31/2022,4/2021,10B,1115,11W00369/4-01,EG8 Med Exp Child,U2,NaN
4,2,Inpatient Hospital Services - Regular Payments,0.0,0.0,0.0,0.0,NaN,Tennessee,3/31/2022,4/2021,10B,1115,11W00369/4-01,EG8 Med Exp Child,U2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,23,Medical Transportation,0.0,NaN,0.0,0.0,NaN,Tennessee,3/31/2022,NaN,NaN,1115,11W00369/4-02,EG8 Med Exp Child,U2,0.0
244,24,Case Management,0.0,NaN,0.0,0.0,NaN,Tennessee,3/31/2022,NaN,NaN,1115,11W00369/4-02,EG8 Med Exp Child,U2,0.0
245,26,ARP Section 9821 COVID Vaccine/Vaccine Adminis...,211033.0,NaN,211033.0,211033.0,NaN,Tennessee,3/31/2022,NaN,NaN,1115,11W00369/4-02,EG8 Med Exp Child,U2,0.0
246,31,Other Services,0.0,NaN,0.0,0.0,NaN,Tennessee,3/31/2022,NaN,NaN,1115,11W00369/4-02,EG8 Med Exp Child,U2,0.0
247,48,Total,68917170.0,NaN,55718721.0,55718721.0,NaN,Tennessee,3/31/2022,NaN,NaN,1115,11W00369/4-02,EG8 Med Exp Child,U2,0.0